import "./globals.css";

import { Toaster } from "@/components/ui/sonner";
import { QueryClientWrapper } from "@/lib/query/provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientWrapper>
          <Toaster />

          <main className="container max-w-screen-md border-l border-r border-dashed min-h-screen">
            {children}

            <footer className="py-8 text-center">
              <span>@thumendess</span>
            </footer>
          </main>
        </QueryClientWrapper>
      </body>
    </html>
  );
}
